### ISSUE TITLE
Versions of python bindings

### ISSUE THREAD

**Issue by jak2030** [Ecotrust/create-utfgrids#2]
Hi, 
Could you please specify the version of OGR bindings you use to run the script successfully?
Currently getting this traceback:

```
WARNING:
 This script assumes a polygon shapefile in spherical mercator projection.
 If any of these assumptions are not true, don't count on the results!
Traceback (most recent call last):
  File "./create_utfgrids.py", line 108, in <module>
    create_utfgrids(shppath, minzoom, maxzoom, outdir, fields)
  File "./create_utfgrids.py", line 44, in create_utfgrids
    polygon_symbolizer = mapnik.PolygonSymbolizer(mapnik.Color('#f2eff9'))
Boost.Python.ArgumentError: Python argument types in
    PolygonSymbolizer.__init__(PolygonSymbolizer, Color)
did not match C++ signature:
    __init__(_object*)
```

**Comment by perrygeo** [comment]
That error is related to mapnik bindings, not OGR

At the time this was written, mapnik 2.x was used. It's not been tested on 3.x. What version of mapnik are you using?

**Comment by jak2030** [comment]
Thanks for getting back so fast. I see. That's the problem!
