### ISSUE TITLE
NoneType Object has no attribute 'GetLayer'

### ISSUE THREAD

**Issue by chimaera8** [Ecotrust/create-utfgrids#7]
Hey there,

first, thanks for the work you put into creat_utfgrids. It's just what I was looking for.

I, however, get the following message trying to convert a shapefile into a UTFGrid. The EPSG is 4326:

Traceback (most recent call last):
  File "c:\create_utfgrids.py", line 108, in <module>
    create_utfgrids(shppath, minzoom, maxzoom, outdir, fields)
  File "c:\create_utfgrids.py", line 34, in create_utfgrids
    layer = ds.GetLayer(layernum)
AttributeError: 'NoneType' object has no attribute 'GetLayer'

Do you have an idea what the issue could be here?

Thanks a lot!

**Comment by chimaera8** [comment]
Sorry for that. It was a question I asked too fast. The error is 1) not related to your script and 2) due to the fact that the shapefile was corrupted... :/ I closed the issue.
